# 25_manuscript_figures_main.R
# ---------------------------------------------------------------------------
# Canonical entry point for the four figures used in the Nature Food
# submission manuscript (`submission_nature_food/Paper_UPF_Argentina_manuscript.tex`).
#
# Figure_1  -> composite results figure from 24_results_section_figures.R
# Figure_2  -> environmental policy heatmap from 20_bundle_table_replacement_figures.R
# Figure_3  -> replacement-basket stacked bars + delta heatmap from 23_ed1_...
# Figure_4  -> 4-scatter Pareto + summary heatmap from figures_upf_argentina.R
#
# Outputs:
#   - output/figures/manuscript/Figure_1 ... Figure_4
#   - submission_nature_food/Figure_1 ... Figure_4
#   - submission_nature_food/figures/Figure_1 ... Figure_4
# ---------------------------------------------------------------------------

detect_project_root <- function() {
  wd <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
  if (file.exists(file.path(wd, "output", "Tabla1_UPF_por_energia_Argentina.csv")) &&
      dir.exists(file.path(wd, "R"))) {
    return(wd)
  }
  parent <- normalizePath(file.path(wd, ".."), winslash = "/", mustWork = FALSE)
  if (dir.exists(parent) &&
      file.exists(file.path(parent, "output", "Tabla1_UPF_por_energia_Argentina.csv")) &&
      dir.exists(file.path(parent, "R"))) {
    return(parent)
  }
  stop("Could not locate project root from working directory: ", wd)
}

root <- if (exists("PROJECT_ROOT")) PROJECT_ROOT else detect_project_root()
PROJECT_ROOT <- root

OUT <- file.path(root, "output")
DEST <- file.path(OUT, "figures", "manuscript")
SUBMISSION_DIR <- file.path(root, "submission_nature_food")
SUBMISSION_FIG_DIR <- file.path(SUBMISSION_DIR, "figures")

dir.create(DEST, showWarnings = FALSE, recursive = TRUE)
dir.create(SUBMISSION_DIR, showWarnings = FALSE, recursive = TRUE)
dir.create(SUBMISSION_FIG_DIR, showWarnings = FALSE, recursive = TRUE)

R_DIR <- file.path(root, "R")

run_r_script <- function(script_name) {
  message("==> sourcing ", script_name)
  source(file.path(R_DIR, script_name), local = new.env(parent = globalenv()))
}

run_root_script <- function(script_path) {
  message("==> sourcing ", basename(script_path))
  source(script_path, local = new.env(parent = globalenv()))
}

# Build upstream figure pools required by the manuscript set.
run_r_script("24_results_section_figures.R")
run_r_script("20_bundle_table_replacement_figures.R")
run_r_script("23_ed1_replacement_baskets_stacked_delta.R")
run_root_script(file.path(root, "figures_upf_argentina.R"))

fig_map <- list(
  Figure_1 = file.path(OUT, "figures", "results_section", "Fig_1_composite"),
  Figure_2 = file.path(OUT, "table_replacement_bundle", "fig04_table5_environment_policy_heatmap"),
  Figure_3 = file.path(OUT, "figures_final", "alternatives", "ED1_replacement_baskets_stacked_delta"),
  Figure_4 = file.path(OUT, "figures", "Fig5_pareto_4scatter_plus")
)

copy_pair <- function(src_base, dst_base) {
  copied_any <- FALSE
  for (ext in c(".pdf", ".png")) {
    src <- paste0(src_base, ext)
    if (!file.exists(src)) {
      message("  MISSING ", src)
      next
    }
    copied_any <- TRUE
    file.copy(src, file.path(DEST, paste0(dst_base, ext)), overwrite = TRUE)
    file.copy(src, file.path(SUBMISSION_DIR, paste0(dst_base, ext)), overwrite = TRUE)
    file.copy(src, file.path(SUBMISSION_FIG_DIR, paste0(dst_base, ext)), overwrite = TRUE)
    message("  copied ", basename(src), " -> ", dst_base, ext)
  }
  copied_any
}

copied <- vapply(names(fig_map), function(nm) copy_pair(fig_map[[nm]], nm), logical(1))

manifest <- c(
  "# Main manuscript figures",
  "",
  "This folder contains the four figures used by `submission_nature_food/Paper_UPF_Argentina_manuscript.tex`.",
  "",
  "## Mapping",
  "- `Figure_1`: `output/figures/results_section/Fig_1_composite`",
  "- `Figure_2`: `output/table_replacement_bundle/fig04_table5_environment_policy_heatmap`",
  "- `Figure_3`: `output/figures_final/alternatives/ED1_replacement_baskets_stacked_delta`",
  "- `Figure_4`: `output/figures/Fig5_pareto_4scatter_plus`",
  "",
  "Generated by `R/25_manuscript_figures_main.R`."
)
writeLines(manifest, file.path(DEST, "README_main_manuscript_figures.md"))

if (!all(copied)) {
  missing_names <- paste(names(copied)[!copied], collapse = ", ")
  stop("Some manuscript figures could not be copied: ", missing_names)
}

message("Done. Main manuscript figures written to:")
message("  - ", DEST)
message("  - ", SUBMISSION_DIR)
message("  - ", SUBMISSION_FIG_DIR)
